### ISSUE TITLE
End Time wrong value when Timezone is not UTC

### ISSUE THREAD

**Issue by cip123** [ChristianLightServices/TimeLight#26]
If I log some time after I stop Clockify and go to `Daily Time Report,` the end time does not respect the local timezone, so, for my timezone, it is 2 hours behind. 

If I click refresh, the entries are displayed correctly.

**Comment by LorenDB** [comment]
I probably just didn't put a proper call in somewhere to get the current time with the proper timezone.

**Comment by LorenDB** [comment]
Can you download one of the AppImages from [this action run](https://github.com/ChristianLightServices/TimeLight/actions/runs/4078489673) and see if it fixes the issue? I reworked some of the timezone stuff, but I don't know if that will fix it or not.

**Comment by cip123** [comment]
Yup, it does. Thank you.

**Comment by cip123** [comment]
I reopened it because this is not yet released.

**Comment by LorenDB** [comment]
Great! I think I will close this, because if anybody else has this issue, they can search all the issues or they can complain and I can tell them it was fixed. :) Thanks for reporting this!

**Comment by LorenDB** [comment]
(And I generally release this whenever I have more than one major change or fix and I don't have anything more big planned.)
